# Generated by Django 5.1.2 on 2024-10-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the ticket.', max_length=100)),
                ('description', models.TextField(help_text='Description of the ticket.')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], help_text='Status of the ticket.', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created date and time of the ticket.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
