# Generated by Django 5.1.2 on 2024-10-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='created_at',
            new_name='created',
        ),
    ]
